Update build-images.yml

diff --git a/.github/workflows/build-images.yml b/.github/workflows/build-images.yml
--- a/.github/workflows/build-images.yml
+++ b/.github/workflows/build-images.yml
@@ -117,29 +117,25 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@main
 
-      - name: Calculate current hash for sync-rtevents
-        id: calculate-hash
+      - name: Generate hash for module
         run: |
           find sync-rtevents -type f -exec sha256sum {} + | sort | sha256sum > sync-rtevents.hash
 
-      - name: Cache previous hash
-        id: cache-previous-hash
-        uses: actions/cache@v3
+      - name: Get previous hash
+        uses: actions/cache@main
         with:
-          path: sync-rtevents.hash.old
+          path: sync-rtevents.hash.prev
           key: sync-rtevents-hash-${{ github.ref_name }}
           restore-keys: sync-rtevents-hash-
 
       - name: Compare hashes
-        id: compare-hash
-        run: |
-          if [ -f sync-rtevents.hash.old ] && cmp -s sync-rtevents.hash sync-rtevents.hash.old; then
-            echo "sync-rtevents unchanged"
-            echo "sync_rtevents_changed=false" >> $GITHUB_ENV
-          else
-            echo "sync-rtevents changed"
-            echo "sync_rtevents_changed=true" >> $GITHUB_ENV
-          fi
+            run: |
+              if [ -f sync-rtevents.hash.prev ] && cmp -s sync-rtevents.hash sync-rtevents.hash.prev; then
+                echo "sync-rtevents unchanged"
+                exit 1  # This will fail the step and job
+              else
+                echo "sync-rtevents changed"
+              fi
 
       - name: Login to GitHub Container Registry
         uses: docker/login-action@master
@@ -160,7 +156,7 @@ jobs:
       - name: Store current hash for future comparisons
         if: env.sync_rtevents_changed == 'true'
         run: |
-          cp sync-rtevents.hash sync-rtevents.hash.old
+          cp sync-rtevents.hash sync-rtevents.hash.prev
 
   # # # # # # # # # # # # # # # # # # # # #
   # # # # # # # # # # # # # # # # # # # # #
